### ISSUE TITLE
Issue with Adding Spectra

### ISSUE THREAD

**Issue by fa-2000** [pymzml/pymzML#274] opened 2021-07-17 18:07 UTC
`import pymzml

s = pymzml.spec.Spectrum()

file_to_read = r'C:\file'

run = pymzml.run.Reader(
file_to_read,
MS1_Precision = 5e-6 ,
MSn_Precision = 20e-6
)

for spec in run:
    s += spec`

When I try to run the above code, I get an error : AttributeError: 'numpy.ndarray' object has no attribute 'items'

The file I am working with contains forty individual scans that I want to average into one spectrum.

**Comment by MKoesters** [comment] 2021-07-20 08:15
Hi @fa-2000 .

Thnaks for using pymzML!
I just tried your code with one of our example files and could not reproduce the error.

Could you give me some information about your mzML file?
What instrument are you using and do you have centroided or profile data?
If you would be able upload the mzML, that would help a lot, else I'll try to reproduce the issue locally somehow.

Best,
Manuel

**Comment by MKoesters** [comment] 2021-08-06 12:41
Closing for now, if this is still an issue, feel free to reopen

**Closed by MKoesters** 2021-08-06 12:41 UTC
Labels: bug, Question
